#!/bin/bash
# vim: set ft=sh

set -eux

ROOT=$PWD

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/concourse/tracker-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install ./vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -skipPackage="vendor" -race -r -p "$@"

./scripts/build

cp -a assets/ Dockerfile $BUILD_DIR
