#!/bin/bash
# vim: set ft=sh

set -e -x

ROOT=$PWD

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/concourse/tracker-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p "$@"

./scripts/build

cd ..
mv tracker-resource $ROOT/build-root
